name: Validate

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        # Blank string allows us to test against version in nvmrc file
        # configured in 'Set up Node.js' down below.
        node: ['', 'lts/*']
    name: Lint & Test (${{ (matrix.node && matrix.node != 'lts/*') && format('node {0}', matrix.node) || matrix.node || 'nvmrc' }})
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - uses: pnpm/action-setup@master

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node }}
          node-version-file: ${{ matrix.node == '' && '.nvmrc' || '' }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: pnpm build && node ./site/makeDocsManifest

      - name: Lint
        run: pnpm lint

      - name: Unit Test
        run: pnpm test:unit
  windows-test:
    strategy:
      matrix:
        # Blank string allows us to test against version in nvmrc file
        # configured in 'Set up Node.js' down below.
        node: ['', 'lts/*']
    name: Windows Tests (${{ (matrix.node && matrix.node != 'lts/*') && format('node {0}', matrix.node) || matrix.node || 'nvmrc' }})
    runs-on: windows-latest
    env:
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - uses: pnpm/action-setup@master

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node }}
          node-version-file: ${{ matrix.node == '' && '.nvmrc' || '' }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Unit Test
        run: pnpm test:unit
  playwright:
    name: Playwright tests
    runs-on: macos-13
    env:
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - uses: pnpm/action-setup@master

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Install Browsers
        run: pnpm playwright install chromium

      - name: Build packages
        run: pnpm build

      - name: Playwright tests
        run: pnpm test:playwright

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-results
          path: test-results/
